import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    Mic,
    Waveform,
    MessageSquare,
    FileAudio,
    ListMusic,
    BarChart,
    Clock,
    Calendar,
    RefreshCw,
    Search,
    Upload,
    Zap,
    Award,
    Building,
    ClipboardCheck,
    Download,
    Edit,
    LogOut,
    Music,
    Rocket,
    Shield,
    PlusCircle,
    Key
  } from "lucide-react"
  
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    file: File,
    fileText: FileText,
    twitter: Twitter,
    check: Check,
    image: Image,
    mic: Mic,
    waveform: Waveform,
    message: MessageSquare,
    fileAudio: FileAudio,
    listMusic: ListMusic,
    chart: BarChart,
    clock: Clock,
    calendar: Calendar,
    refresh: RefreshCw,
    search: Search,
    upload: Upload,
    zap: Zap,
    award: Award,
    building: Building,
    clipboard: ClipboardCheck,
    download: Download,
    edit: Edit,
    logout: LogOut,
    music: Music,
    rocket: Rocket,
    shield: Shield,
    plus: PlusCircle,
    key: Key
  }